### ISSUE TITLE
Display locality-only feed titles differently?

### ISSUE THREAD

**Issue by pkoms** [votinginfoproject/Metis#205]
As I'm starting to run CA County feeds in Metis, I'm realizing that, as we roll all of our QA over from quick_feed to Metis, it would be extremely helpful to have the name of the county displayed on the feed dashboard and in the feed title.

As a feature, I think it makes sense to frame it like this:
If a feed has only one locality object, where we currently display "[State]," display "[Locality Title], [State]", and change the URLs from "[Date]-[State]-[Election-type]" to "[Date]-[Locality Title]-[State]-[Election Title]".

I'd also be curious to get @robweychert's input on this.

**Comment by MariaDemocracyWorks** [comment]
Does this still seem worthwhile, @jungshadow, if we're moving away from counties submitting data?

**Comment by jungshadow** [comment]
Good point. I'll mark as invalid and close. We can reopen if we need it.
